language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script:
  - bash -ex .travis-opam.sh
  - eval `opam config env`; make js
  - eval `opam config env`; make doc
  - eval `opam config env`; bash -ex .ci-indent.sh
env:
  - OCAML_VERSION=4.02 PACKAGE=bulletml
