language: c
sudo: false
addons:
  apt:
    packages:
    - ocaml-nox
    - libpcre3-dev
    - libsdl1.2-dev
    - m4
    - pkg-config
cache:
  directories:
    - $HOME/opam-install
    - $HOME/.opam
script:
  - bash -ex .travis-ci.sh
env:
  - OCAML_VERSION=4.02 OCAML_FULL_VERSION=4.02.3 PACKAGE=bulletml
